spring:
  cloud:
    stream:
      bindings:
        input:
          binder: kafka
          destination: delay
#          group: flight-watch
      function:
        definition: delayNotification
  application:
    name: flight-watch
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
#server:
#  port: 8082
